### ISSUE TITLE
Duplication bug with Crafting Browser

### ISSUE THREAD

**Issue by sixtysixone** [gigaherz/Ender-Rift#49]
Steps to reproduce:

1) Place Crafting Browser. Doesn't need inventory, just use as crafting table.
2) Put 4 stone in pattern to create 4 stone bricks
3) Shift+Click bricks in crafting result area (shift+click to "use all ingredients placed")

Expected: 4 bricks (1 recipe output)
Actual: 8 bricks (2 recipe output)

Works with any recipe. Creates one extra of whatever you're crafting when you use shift+click. Have ingredients for 9 gold blocks, shift+click gets you 10 gold blocks.

**Comment by gigaherz** [comment]
Oof I'll take a look as soon as I can.

**Comment by sixtysixone** [comment]
I have a suspicion this might be related to inventory tweaks renewed or similar mod(s) (unconfirmed).

1) You check recipe and place crafting result into output, in CraftingBrowserContainer.java `slotChangedCraftingGrid`
2) Shift+click:
  A) Inventory tweaks (or whatever?) sees a stack of 1 item existing in output, and transfers it.
  B) Shift+click crafts as many as it can and transfers them.

**Comment by gigaherz** [comment]
Sorry that I took so long to fix.
The bug was interesting, because it only happened when there was none of the output already in your inventory.
So, first craft -> dupe
Second craft -> ok
I happened to try this time with something I didn't already have, and *magic*. Turns out I had a bug where it was trying to insert in the crafting slot itself, which added the items to themselves, duplicating the count.
Already published v2.2.7.1 and v2.2.11 on curseforge, which should fix it.
