### ISSUE TITLE
[1.16.5]There's no energy, but it still works

### ISSUE THREAD

**Issue by GaN601** [gigaherz/Ender-Rift#50]
![image](https://user-images.githubusercontent.com/80253667/119148012-aca3e580-ba7e-11eb-81bc-2564b2907207.png)
How much storage space can it provide per 1K RF?
Or just fixed energy can provide access to unlimited storage space?
I want to be able to set a formula. For example, if you store 1K items, you need 100 RF

**Comment by gigaherz** [comment]
There's 2 separate kinds of powering: the energy you provide to the rift structure, and the energy you provide to the inventory network.
Your situation seems to be that the inventory network is not powered. You need a Driver block connected to the same network as the interface, to provide power to the inventory network.

**Comment by GaN601** [comment]
> There's 2 separate kinds of powering: the energy you provide to the rift structure, and the energy you provide to the inventory network.
> Your situation seems to be that the inventory network is not powered. You need a Driver block connected to the same network as the interface, to provide power to the inventory network.

I didn't power the rift, but I can still access it using the panel

**Comment by GaN601** [comment]
> There's 2 separate kinds of powering: the energy you provide to the rift structure, and the energy you provide to the inventory network.
> Your situation seems to be that the inventory network is not powered. You need a Driver block connected to the same network as the interface, to provide power to the inventory network.

Is this inconsistent with the introduction? I think the introduction says it needs energy

**Comment by gigaherz** [comment]
Okay so the way it's supposed to work:
The rift takes power per tick, based on the number of items inside it: `ceil(pow(usedSlots, 0.8))`, meaning if you have 1000 slots used, it uses 252 per tick. 1000000 slots used, it will consume 63096 per tick.
The inventory network uses energy on insert/extract operations, based on how many slots it's currently managing. There's a linear factor and a quadratic factor, configurable. It's this "configurable" that is a problem, because I never implemented configurations when porting to 1.13+, so all the values default to 0.
![image](https://user-images.githubusercontent.com/685851/119161992-2b3a5c00-ba5a-11eb-9f7e-feb194057b4a.png)
