### ISSUE TITLE
Help with moving contents to new world.

### ISSUE THREAD

**Issue by Furious1964** [gigaherz/Ender-Rift#51]
Is there a way to move the contents of the Ender Rift to another save? My world is corrupted and I need to get the items.

**Comment by gigaherz** [comment]
if you copy the savefolder/data/enderRiftStorageManager.dat file you will get the data into the new save, but you will still have to use commands to spawn an orb with the right rift ID, since the id counters are stored in that same file. You can use NBT Explorer to figure out what ID to use.

Eg:

![image](https://user-images.githubusercontent.com/685851/124020983-47cb9b80-d9eb-11eb-9c52-4b91556e5c9c.png)

In this case rift id 1 would be what you want,  and you could spawn it by doing:
```
/give @p enderrift:rift_orb{RiftId:1}
```

**Comment by Furious1964** [comment]
Thank you, Sir. Will try this and hope that that's not corrupted too.
